### ISSUE TITLE
Wisteria trees can sometimes spawn with missing log blocks 

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Environmental#26]
![image](https://user-images.githubusercontent.com/38932715/93729726-999ce680-fb7a-11ea-9215-2b9644eb8565.png)
Sorry if this isn't fixable or something. You told me something in the call when I talked about this but I couldn't hear you.

**Comment by bageldotjpg** [comment]
dont think this is occuring anymore
