### ISSUE TITLE
Sawmills can't Vertical Planks from Planks or vice versa

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Environmental#40]
This one may be intended, not sure.

**Comment by bageldotjpg** [comment]
They can make vertical planks already though? Also chests wouldn't be possible, since it would require two logs and Sawmills take an input of one item

**Comment by WitheredWasabi** [comment]
Oh yeah, didn't think about that. Sorry

**Comment by bageldotjpg** [comment]
decided not gonna do this since you cant do vertical slabs to slabs or vice versa in stonecutter
