### ISSUE TITLE
Bug/conflict with "More Waterlogging" mod

### ISSUE THREAD

**Issue by iCeCoCaCoLa64** [minecraftabnormals/Environmental#71]
The [**More Waterlogging**](https://www.curseforge.com/minecraft/mc-mods/more-waterlogging) mod allows many more types of blocks to be waterlogged (much like Bedrock edition), and one of these block types is leaves.  
When using More Waterlogging with Environmental, wisteria trees naturally generate with all their leaves waterlogged. This doesn't happen with any other mod-added trees, including willow trees— this problem seems to be completely exclusive to wisteria trees. Even if compatibility with other mods isn't exactly a priority at the moment, the fact that this *only* happens with wisteria trees makes me think there's some problem with them that might be worth looking into, so I figured I'd report it.

![2020-10-13_00 31 37](https://user-images.githubusercontent.com/25655781/95816401-03795d80-0ced-11eb-8466-ecebc1d9b50b.png)

**Comment by bageldotjpg** [comment]
fixed in dev
